del /s /q *.dcu
del /s /q *.exe
del /s /q *.log
del /s /q *.dsk
del /s /q *.identcache
del /s /q *.stat
del /s /q *.local
del /s /q *.~*
rmdir /S /Q Win32
rmdir /S /Q Win64
rmdir /S /Q backup
rmdir /S /Q __history
rmdir /S /Q __recovery
